using Luminfield.Game;
using Xunit;

namespace Luminfield.Tests;

public sealed class PlaytestScenarioRegistryTests
{
    private static readonly (
        string Flag,
        PlaytestScenarioId Scenario
    )[] ExpectedScenarios =
    [
        ("--playtest-door", PlaytestScenarioId.Door),
        ("--playtest-cottage", PlaytestScenarioId.Cottage),
        (
            "--playtest-cottage-upgrade-ready",
            PlaytestScenarioId.CottageUpgradeReady
        ),
        (
            "--playtest-cottage-upgrade-in-progress",
            PlaytestScenarioId.CottageUpgradeInProgress
        ),
        (
            "--playtest-cottage-upgrade-completed",
            PlaytestScenarioId.CottageUpgradeCompleted
        ),
        (
            "--playtest-cottage-second-upgrade-ready",
            PlaytestScenarioId.CottageSecondUpgradeReady
        ),
        (
            "--playtest-cottage-second-upgrade-in-progress",
            PlaytestScenarioId.CottageSecondUpgradeInProgress
        ),
        (
            "--playtest-cottage-kitchen",
            PlaytestScenarioId.CottageKitchen
        ),
        (
            "--playtest-cottage-kitchen-panel",
            PlaytestScenarioId.CottageKitchenPanel
        ),
        (
            "--playtest-cottage-pantry",
            PlaytestScenarioId.CottagePantry
        ),
        (
            "--playtest-cottage-pantry-panel",
            PlaytestScenarioId.CottagePantryPanel
        ),
        (
            "--playtest-cottage-meals-en",
            PlaytestScenarioId.CottageMealsEnglish
        ),
        (
            "--playtest-homestead-workshop-ready",
            PlaytestScenarioId.HomesteadWorkshopReady
        ),
        (
            "--playtest-homestead-workshop-in-progress",
            PlaytestScenarioId.HomesteadWorkshopInProgress
        ),
        (
            "--playtest-homestead-workshop-completed",
            PlaytestScenarioId.HomesteadWorkshopCompleted
        ),
        (
            "--playtest-greenhouse-ready",
            PlaytestScenarioId.GreenhouseReady
        ),
        (
            "--playtest-greenhouse-in-progress",
            PlaytestScenarioId.GreenhouseInProgress
        ),
        (
            "--playtest-greenhouse-exterior-completed",
            PlaytestScenarioId.GreenhouseExteriorCompleted
        ),
        (
            "--playtest-greenhouse-completed",
            PlaytestScenarioId.GreenhouseCompleted
        ),
        (
            "--playtest-greenhouse-cistern",
            PlaytestScenarioId.GreenhouseCistern
        ),
        (
            "--playtest-starfeather-coop-ready",
            PlaytestScenarioId.StarfeatherCoopReady
        ),
        (
            "--playtest-starfeather-coop-in-progress",
            PlaytestScenarioId.StarfeatherCoopInProgress
        ),
        (
            "--playtest-starfeather-coop-grazing",
            PlaytestScenarioId.StarfeatherCoopGrazing
        ),
        (
            "--playtest-starfeather-coop-chick",
            PlaytestScenarioId.StarfeatherCoopChick
        ),
        (
            "--playtest-starfeather-coop-adult",
            PlaytestScenarioId.StarfeatherCoopAdult
        ),
        (
            "--playtest-starfeather-coop-nest-blocked-en",
            PlaytestScenarioId.StarfeatherCoopNestBlockedEnglish
        ),
        (
            "--playtest-moonfleece-barn-ready",
            PlaytestScenarioId.MoonfleeceBarnReady
        ),
        (
            "--playtest-moonfleece-barn-in-progress",
            PlaytestScenarioId.MoonfleeceBarnInProgress
        ),
        (
            "--playtest-moonfleece-barn-grazing",
            PlaytestScenarioId.MoonfleeceBarnGrazing
        ),
        (
            "--playtest-moonfleece-barn-juvenile",
            PlaytestScenarioId.MoonfleeceBarnJuvenile
        ),
        (
            "--playtest-moonfleece-barn-rack-blocked-en",
            PlaytestScenarioId.MoonfleeceBarnRackBlockedEnglish
        ),
        (
            "--playtest-dewhorn-grazing",
            PlaytestScenarioId.DewhornGrazing
        ),
        (
            "--playtest-dewhorn-milking-blocked-en",
            PlaytestScenarioId.DewhornMilkingBlockedEnglish
        ),
        (
            "--playtest-livestock-automation-console",
            PlaytestScenarioId.LivestockAutomationConsole
        ),
        (
            "--playtest-livestock-automation-panel",
            PlaytestScenarioId.LivestockAutomationPanel
        ),
        (
            "--playtest-livestock-automation-panel-en",
            PlaytestScenarioId.LivestockAutomationPanelEnglish
        ),
        (
            "--playtest-livestock-automation-construction",
            PlaytestScenarioId.LivestockAutomationConstruction
        ),
        ("--playtest-crops", PlaytestScenarioId.Crops),
        (
            "--playtest-gleamrise-crops",
            PlaytestScenarioId.GleamriseCrops
        ),
        (
            "--playtest-gleamrise-season",
            PlaytestScenarioId.GleamriseSeason
        ),
        (
            "--playtest-rainveil-crops",
            PlaytestScenarioId.RainveilCrops
        ),
        (
            "--playtest-starharvest-crops",
            PlaytestScenarioId.StarharvestCrops
        ),
        (
            "--playtest-starharvest-market-gate",
            PlaytestScenarioId.StarharvestMarketGate
        ),
        (
            "--playtest-starharvest-market",
            PlaytestScenarioId.StarharvestMarket
        ),
        (
            "--playtest-starharvest-market-showcase",
            PlaytestScenarioId.StarharvestMarketShowcase
        ),
        (
            "--playtest-starharvest-market-result",
            PlaytestScenarioId.StarharvestMarketResult
        ),
        (
            "--playtest-starharvest-market-shop",
            PlaytestScenarioId.StarharvestMarketShop
        ),
        (
            "--playtest-starharvest-market-showcase-en",
            PlaytestScenarioId.StarharvestMarketShowcaseEnglish
        ),
        (
            "--playtest-gleamrise-festival-gate",
            PlaytestScenarioId.GleamriseFestivalGate
        ),
        (
            "--playtest-gleamrise-festival",
            PlaytestScenarioId.GleamriseFestival
        ),
        (
            "--playtest-gleamrise-festival-challenge",
            PlaytestScenarioId.GleamriseFestivalChallenge
        ),
        (
            "--playtest-gleamrise-festival-result",
            PlaytestScenarioId.GleamriseFestivalResult
        ),
        (
            "--playtest-gleamrise-festival-exchange",
            PlaytestScenarioId.GleamriseFestivalExchange
        ),
        (
            "--playtest-gleamrise-festival-challenge-en",
            PlaytestScenarioId.GleamriseFestivalChallengeEnglish
        ),
        (
            "--playtest-longnight-feast-gate",
            PlaytestScenarioId.LongnightFeastGate
        ),
        (
            "--playtest-longnight-feast",
            PlaytestScenarioId.LongnightFeast
        ),
        (
            "--playtest-longnight-feast-activity",
            PlaytestScenarioId.LongnightFeastActivity
        ),
        (
            "--playtest-longnight-feast-result",
            PlaytestScenarioId.LongnightFeastResult
        ),
        (
            "--playtest-longnight-feast-stall",
            PlaytestScenarioId.LongnightFeastStall
        ),
        (
            "--playtest-longnight-feast-activity-en",
            PlaytestScenarioId.LongnightFeastActivityEnglish
        ),
        (
            "--playtest-longnight-feast-wrong-tool",
            PlaytestScenarioId.LongnightFeastWrongTool
        ),
        (
            "--playtest-firefly-tide-gate",
            PlaytestScenarioId.FireflyTideGate
        ),
        (
            "--playtest-firefly-tide",
            PlaytestScenarioId.FireflyTide
        ),
        (
            "--playtest-firefly-tide-activity",
            PlaytestScenarioId.FireflyTideActivity
        ),
        (
            "--playtest-firefly-tide-result",
            PlaytestScenarioId.FireflyTideResult
        ),
        (
            "--playtest-firefly-tide-shop",
            PlaytestScenarioId.FireflyTideShop
        ),
        (
            "--playtest-firefly-tide-activity-en",
            PlaytestScenarioId.FireflyTideActivityEnglish
        ),
        (
            "--playtest-firefly-tide-wrong-tool",
            PlaytestScenarioId.FireflyTideWrongTool
        ),
        (
            "--playtest-longnight-homestead",
            PlaytestScenarioId.LongnightHomestead
        ),
        (
            "--playtest-longnight-emporium",
            PlaytestScenarioId.LongnightEmporium
        ),
        (
            "--playtest-longnight-snow-forecast",
            PlaytestScenarioId.LongnightSnowForecast
        ),
        (
            "--playtest-longnight-snow",
            PlaytestScenarioId.LongnightSnow
        ),
        (
            "--playtest-longnight-snow-indoor",
            PlaytestScenarioId.LongnightSnowIndoor
        ),
        (
            "--playtest-longnight-snow-clear",
            PlaytestScenarioId.LongnightSnowClear
        ),
        ("--playtest-economy", PlaytestScenarioId.Economy),
        ("--playtest-processor", PlaytestScenarioId.Processor),
        (
            "--playtest-multi-processor",
            PlaytestScenarioId.MultiProcessorBatch
        ),
        (
            "--playtest-moonpearl-egg-press",
            PlaytestScenarioId.MoonpearlEggPress
        ),
        ("--playtest-archive-gift", PlaytestScenarioId.ArchiveGift),
        ("--playtest-archive", PlaytestScenarioId.Archive),
        ("--playtest-archive-door", PlaytestScenarioId.ArchiveDoor),
        ("--playtest-crop-codex-desk", PlaytestScenarioId.CropCodexDesk),
        (
            "--playtest-crop-codex-partial",
            PlaytestScenarioId.CropCodexPartial
        ),
        (
            "--playtest-crop-codex-reward-ready",
            PlaytestScenarioId.CropCodexRewardReady
        ),
        (
            "--playtest-crop-codex-reward-claimed-en",
            PlaytestScenarioId.CropCodexRewardClaimedEnglish
        ),
        (
            "--playtest-crop-codex-wrong-tool",
            PlaytestScenarioId.CropCodexWrongTool
        ),
        (
            "--playtest-crop-codex-discount-shop",
            PlaytestScenarioId.CropCodexDiscountShop
        ),
        (
            "--playtest-cooking-codex-unknown",
            PlaytestScenarioId.CookingCodexUnknown
        ),
        (
            "--playtest-cooking-codex-partial",
            PlaytestScenarioId.CookingCodexPartial
        ),
        (
            "--playtest-cooking-codex-reward-ready",
            PlaytestScenarioId.CookingCodexRewardReady
        ),
        (
            "--playtest-cooking-codex-reward-claimed-en",
            PlaytestScenarioId.CookingCodexRewardClaimedEnglish
        ),
        (
            "--playtest-cooking-codex-reward-meals-en",
            PlaytestScenarioId.CookingCodexRewardMealsEnglish
        ),
        (
            "--playtest-artisan-codex-unknown",
            PlaytestScenarioId.ArtisanCodexUnknown
        ),
        (
            "--playtest-artisan-codex-partial",
            PlaytestScenarioId.ArtisanCodexPartial
        ),
        (
            "--playtest-artisan-codex-reward-ready",
            PlaytestScenarioId.ArtisanCodexRewardReady
        ),
        (
            "--playtest-artisan-codex-reward-claimed-en",
            PlaytestScenarioId.ArtisanCodexRewardClaimedEnglish
        ),
        (
            "--playtest-artisan-codex-reward-shipping-en",
            PlaytestScenarioId.ArtisanCodexRewardShippingEnglish
        ),
        (
            "--playtest-seasonal-forage",
            PlaytestScenarioId.SeasonalForage
        ),
        (
            "--playtest-seasonal-forage-wrong-tool",
            PlaytestScenarioId.SeasonalForageWrongTool
        ),
        (
            "--playtest-seasonal-forage-stardust-map",
            PlaytestScenarioId.SeasonalForageStardustMap
        ),
        (
            "--playtest-forage-codex-partial",
            PlaytestScenarioId.ForageCodexPartial
        ),
        (
            "--playtest-forage-codex-reward-ready",
            PlaytestScenarioId.ForageCodexRewardReady
        ),
        (
            "--playtest-forage-codex-reward-claimed-en",
            PlaytestScenarioId.ForageCodexRewardClaimedEnglish
        ),
        ("--playtest-fishing", PlaytestScenarioId.Fishing),
        (
            "--playtest-fishing-minigame",
            PlaytestScenarioId.FishingMinigame
        ),
        (
            "--playtest-fishing-gear",
            PlaytestScenarioId.FishingGear
        ),
        (
            "--playtest-fishing-collection",
            PlaytestScenarioId.FishingCollection
        ),
        (
            "--playtest-fishing-donation",
            PlaytestScenarioId.FishingDonation
        ),
        (
            "--playtest-fish-codex-partial",
            PlaytestScenarioId.FishCodexPartial
        ),
        (
            "--playtest-fish-codex-complete-en",
            PlaytestScenarioId.FishCodexCompleteEnglish
        ),
        (
            "--playtest-crystal-grotto-entry",
            PlaytestScenarioId.CrystalGrottoEntry
        ),
        (
            "--playtest-crystal-grotto-basic",
            PlaytestScenarioId.CrystalGrottoBasic
        ),
        (
            "--playtest-crystal-grotto-upgrade",
            PlaytestScenarioId.CrystalGrottoUpgrade
        ),
        (
            "--playtest-crystal-grotto-deep",
            PlaytestScenarioId.CrystalGrottoDeep
        ),
        ("--playtest-deep-mine", PlaytestScenarioId.DeepMine),
        (
            "--playtest-mineral-codex-complete-en",
            PlaytestScenarioId.MineralCodexCompleteEnglish
        ),
        (
            "--playtest-crystal-vale-starlight-panel",
            PlaytestScenarioId.CrystalValeStarlightPanel
        ),
        (
            "--playtest-crystal-vale-starlight-restored",
            PlaytestScenarioId.CrystalValeStarlightRestored
        ),
        (
            "--playtest-starfall-ruins-entry",
            PlaytestScenarioId.StarfallRuinsEntry
        ),
        (
            "--playtest-starfall-ruins-combat",
            PlaytestScenarioId.StarfallRuinsCombat
        ),
        (
            "--playtest-starfall-ruins-artifacts",
            PlaytestScenarioId.StarfallRuinsArtifacts
        ),
        (
            "--playtest-artifact-codex-donation-en",
            PlaytestScenarioId.ArtifactCodexDonationEnglish
        ),
        (
            "--playtest-starfall-ruins-starlight-panel",
            PlaytestScenarioId.StarfallRuinsStarlightPanel
        ),
        (
            "--playtest-starfall-ruins-starlight-restored",
            PlaytestScenarioId.StarfallRuinsStarlightRestored
        ),
        (
            "--playtest-sixfold-star-gate",
            PlaytestScenarioId.SixfoldStarGate
        ),
        (
            "--playtest-sixfold-star-gate-panel",
            PlaytestScenarioId.SixfoldStarGatePanel
        ),
        (
            "--playtest-liora-event-one",
            PlaytestScenarioId.LioraEventOne
        ),
        (
            "--playtest-liora-event-two",
            PlaytestScenarioId.LioraEventTwo
        ),
        (
            "--playtest-tavi-event-one",
            PlaytestScenarioId.TaviEventOne
        ),
        (
            "--playtest-tavi-event-two",
            PlaytestScenarioId.TaviEventTwo
        ),
        (
            "--playtest-nemi-event-one",
            PlaytestScenarioId.NemiEventOne
        ),
        (
            "--playtest-nemi-event-two",
            PlaytestScenarioId.NemiEventTwo
        ),
        (
            "--playtest-kael-event-one",
            PlaytestScenarioId.KaelEventOne
        ),
        (
            "--playtest-kael-event-two",
            PlaytestScenarioId.KaelEventTwo
        ),
        (
            "--playtest-sela-event-one",
            PlaytestScenarioId.SelaEventOne
        ),
        (
            "--playtest-sela-event-two",
            PlaytestScenarioId.SelaEventTwo
        ),
        (
            "--playtest-orin-event-one",
            PlaytestScenarioId.OrinEventOne
        ),
        (
            "--playtest-orin-event-two",
            PlaytestScenarioId.OrinEventTwo
        ),
        (
            "--playtest-elowen-event-one",
            PlaytestScenarioId.ElowenEventOne
        ),
        (
            "--playtest-elowen-event-two",
            PlaytestScenarioId.ElowenEventTwo
        ),
        (
            "--playtest-vessa-event-one",
            PlaytestScenarioId.VessaEventOne
        ),
        (
            "--playtest-vessa-event-two",
            PlaytestScenarioId.VessaEventTwo
        ),
        (
            "--playtest-vessa-event-wrong-tool",
            PlaytestScenarioId.VessaEventWrongTool
        ),
        (
            "--playtest-relationship-mails-en",
            PlaytestScenarioId.RelationshipMailsEnglish
        ),
        (
            "--playtest-village-expansion-wave-3",
            PlaytestScenarioId.VillageExpansionWave3
        ),
        (
            "--playtest-village-expansion-wave-3-indoor",
            PlaytestScenarioId.VillageExpansionWave3Indoor
        ),
        (
            "--playtest-village-expansion-wave-3-dialogue-en",
            PlaytestScenarioId.VillageExpansionWave3DialogueEnglish
        ),
        (
            "--playtest-village-expansion-wave-3-wrong-tool",
            PlaytestScenarioId.VillageExpansionWave3WrongTool
        ),
        (
            "--playtest-yvara-event-one",
            PlaytestScenarioId.YvaraEventOne
        ),
        (
            "--playtest-yvara-event-two",
            PlaytestScenarioId.YvaraEventTwo
        ),
        (
            "--playtest-wave-3-relationship-mails-en",
            PlaytestScenarioId.Wave3RelationshipMailsEnglish
        ),
        (
            "--playtest-workshop-tavi",
            PlaytestScenarioId.WorkshopTavi
        ),
        ("--playtest-workshop", PlaytestScenarioId.Workshop),
        (
            "--playtest-workshop-door",
            PlaytestScenarioId.WorkshopDoor
        ),
        (
            "--playtest-tea-house-vessa",
            PlaytestScenarioId.TeaHouseVessa
        ),
        ("--playtest-tea-house", PlaytestScenarioId.TeaHouse),
        (
            "--playtest-tea-house-door",
            PlaytestScenarioId.TeaHouseDoor
        ),
        (
            "--playtest-emporium-orin",
            PlaytestScenarioId.EmporiumOrin
        ),
        ("--playtest-emporium", PlaytestScenarioId.Emporium),
        (
            "--playtest-emporium-door",
            PlaytestScenarioId.EmporiumDoor
        ),
        (
            "--playtest-emporium-rotation",
            PlaytestScenarioId.EmporiumRotation
        ),
        (
            "--playtest-emporium-restday-door",
            PlaytestScenarioId.EmporiumRestdayDoor
        ),
        (
            "--playtest-starlight-post-nemi",
            PlaytestScenarioId.StarlightPostNemi
        ),
        (
            "--playtest-starlight-post",
            PlaytestScenarioId.StarlightPost
        ),
        (
            "--playtest-starlight-post-wrong-tool",
            PlaytestScenarioId.StarlightPostWrongTool
        ),
        (
            "--playtest-starlight-post-door",
            PlaytestScenarioId.StarlightPostDoor
        ),
        (
            "--playtest-starfall-watch-kael",
            PlaytestScenarioId.StarfallWatchKael
        ),
        (
            "--playtest-starfall-watch",
            PlaytestScenarioId.StarfallWatch
        ),
        (
            "--playtest-starfall-watch-wrong-tool",
            PlaytestScenarioId.StarfallWatchWrongTool
        ),
        (
            "--playtest-starfall-watch-door",
            PlaytestScenarioId.StarfallWatchDoor
        ),
        (
            "--playtest-village-dialogue",
            PlaytestScenarioId.VillageDialogue
        ),
        (
            "--playtest-sela-dialogue",
            PlaytestScenarioId.SelaDialogue
        ),
        (
            "--playtest-village-expansion",
            PlaytestScenarioId.VillageExpansion
        ),
        (
            "--playtest-village-expansion-archive",
            PlaytestScenarioId.VillageExpansionArchive
        ),
        (
            "--playtest-village-expansion-dialogue-en",
            PlaytestScenarioId.VillageExpansionDialogueEnglish
        ),
        (
            "--playtest-village-expansion-wrong-tool",
            PlaytestScenarioId.VillageExpansionWrongTool
        ),
        (
            "--playtest-npc-pathfinding",
            PlaytestScenarioId.NpcPathfinding
        ),
        (
            "--playtest-village-restday-en",
            PlaytestScenarioId.VillageRestdayEnglish
        ),
        (
            "--playtest-village-rain-schedule",
            PlaytestScenarioId.VillageRainSchedule
        ),
        (
            "--playtest-village-rainveil-schedule",
            PlaytestScenarioId.VillageRainveilSchedule
        ),
        ("--playtest-village", PlaytestScenarioId.Village),
        (
            "--playtest-world-aspect-boundary",
            PlaytestScenarioId.WorldAspectBoundary
        ),
        (
            "--playtest-rainveil-world-aspect",
            PlaytestScenarioId.RainveilWorldAspect
        ),
        (
            "--playtest-starharvest-world-aspect",
            PlaytestScenarioId.StarharvestWorldAspect
        ),
        (
            "--playtest-longnight-world-aspect",
            PlaytestScenarioId.LongnightWorldAspect
        ),
        (
            "--playtest-rainveil-world-tree-rain",
            PlaytestScenarioId.RainveilWorldTreeRain
        ),
        (
            "--playtest-starharvest-world-crystal-stardust",
            PlaytestScenarioId.StarharvestWorldCrystalStardust
        ),
        (
            "--playtest-world-woods-grove",
            PlaytestScenarioId.WorldWoodsGrove
        ),
        (
            "--playtest-world-meadow-circle",
            PlaytestScenarioId.WorldMeadowCircle
        ),
        (
            "--playtest-world-crystal-ridge",
            PlaytestScenarioId.WorldCrystalRidge
        ),
        (
            "--playtest-world-wetland-islet",
            PlaytestScenarioId.WorldWetlandIslet
        ),
        (
            "--playtest-world-ruins-colonnade",
            PlaytestScenarioId.WorldRuinsColonnade
        ),
        ("--playtest-world", PlaytestScenarioId.World),
        ("--playtest-gate", PlaytestScenarioId.Gate),
        ("--playtest-backpack", PlaytestScenarioId.Backpack),
        ("--playtest-resource", PlaytestScenarioId.Resource),
        ("--playtest-target", PlaytestScenarioId.Target),
        ("--playtest-phase-a", PlaytestScenarioId.PhaseA),
        (
            "--playtest-phase-a-summary",
            PlaytestScenarioId.PhaseASummary
        ),
        ("--playtest-phase-a-rain", PlaytestScenarioId.PhaseARain),
        (
            "--playtest-resource-respawn",
            PlaytestScenarioId.ResourceRespawn
        ),
        ("--playtest-crafting", PlaytestScenarioId.Crafting),
        ("--playtest-placeables", PlaytestScenarioId.Placeables),
        (
            "--playtest-chest-placement",
            PlaytestScenarioId.ChestPlacement
        ),
        ("--playtest-storage", PlaytestScenarioId.Storage),
        (
            "--playtest-commission-offer",
            PlaytestScenarioId.CommissionOffer
        ),
        (
            "--playtest-commission-ready",
            PlaytestScenarioId.CommissionReady
        ),
        (
            "--playtest-commission-ready-en",
            PlaytestScenarioId.CommissionReadyEnglish
        ),
        (
            "--playtest-commission-map",
            PlaytestScenarioId.CommissionMap
        ),
        (
            "--playtest-weekly-commission-offer",
            PlaytestScenarioId.WeeklyCommissionOffer
        ),
        (
            "--playtest-weekly-commission-stage-ready",
            PlaytestScenarioId.WeeklyCommissionStageReady
        ),
        (
            "--playtest-weekly-commission-reward-ready",
            PlaytestScenarioId.WeeklyCommissionRewardReady
        ),
        (
            "--playtest-weekly-commission-map",
            PlaytestScenarioId.WeeklyCommissionMap
        ),
        (
            "--playtest-mailbox-unread",
            PlaytestScenarioId.MailboxUnread
        ),
        (
            "--playtest-mail-panel",
            PlaytestScenarioId.MailPanel
        ),
        (
            "--playtest-mail-reward",
            PlaytestScenarioId.MailReward
        ),
        ("--playtest-starlight-map", PlaytestScenarioId.StarlightMap),
        (
            "--playtest-starlight-map-restored",
            PlaytestScenarioId.StarlightMapRestored
        ),
        (
            "--playtest-starlight-panel",
            PlaytestScenarioId.StarlightPanel
        ),
        (
            "--playtest-starlight-restored",
            PlaytestScenarioId.StarlightRestored
        ),
        (
            "--playtest-starlight-restored-en",
            PlaytestScenarioId.StarlightRestoredEnglish
        ),
        (
            "--playtest-homestead-starlight-dormant",
            PlaytestScenarioId.HomesteadStarlightDormant
        ),
        (
            "--playtest-homestead-starlight-wrong-tool",
            PlaytestScenarioId.HomesteadStarlightWrongTool
        ),
        (
            "--playtest-homestead-starlight-restored",
            PlaytestScenarioId.HomesteadStarlightRestored
        ),
        (
            "--playtest-homestead-starlight-panel",
            PlaytestScenarioId.HomesteadStarlightPanel
        ),
        (
            "--playtest-homestead-starlight-panel-en",
            PlaytestScenarioId.HomesteadStarlightPanelEnglish
        ),
        (
            "--playtest-meadow-starlight-dormant",
            PlaytestScenarioId.MeadowStarlightDormant
        ),
        (
            "--playtest-meadow-starlight-restored",
            PlaytestScenarioId.MeadowStarlightRestored
        ),
        (
            "--playtest-meadow-starlight-panel",
            PlaytestScenarioId.MeadowStarlightPanel
        ),
        (
            "--playtest-meadow-starlight-panel-en",
            PlaytestScenarioId.MeadowStarlightPanelEnglish
        ),
        (
            "--playtest-meadow-pollination",
            PlaytestScenarioId.MeadowPollination
        ),
        (
            "--playtest-moonwater-starlight-panel",
            PlaytestScenarioId.MoonwaterStarlightPanel
        ),
        (
            "--playtest-quality-crafting",
            PlaytestScenarioId.QualityCrafting
        ),
        (
            "--playtest-quality-backpack-en",
            PlaytestScenarioId.QualityBackpackEnglish
        ),
        (
            "--playtest-quality-backpack",
            PlaytestScenarioId.QualityBackpack
        ),
        ("--playtest-quality", PlaytestScenarioId.Quality),
        (
            "--playtest-farming-specialization",
            PlaytestScenarioId.FarmingSpecialization
        ),
        (
            "--playtest-orchard-hives",
            PlaytestScenarioId.OrchardHives
        ),
        ("--playtest-farm", PlaytestScenarioId.Farm)
    ];

    [Fact]
    public void KnownFlagsAreUniqueAndPreserveTheExistingCatalog()
    {
        var expectedFlags = ExpectedScenarios
            .Select(scenario => scenario.Flag)
            .ToArray();

        Assert.Equal(expectedFlags, PlaytestScenarioRegistry.KnownFlags);
        Assert.Equal(
            expectedFlags.Length,
            expectedFlags.Distinct(StringComparer.Ordinal).Count()
        );
        Assert.Equal(
            Enum.GetValues<PlaytestScenarioId>().Length,
            expectedFlags.Length
        );

        foreach (var expected in ExpectedScenarios)
        {
            Assert.Equal(
                expected.Scenario,
                PlaytestScenarioRegistry.ResolveScenario([expected.Flag])
            );
        }
    }

    [Fact]
    public void RegistrationOrderWinsWhenMultipleFlagsArePresent()
    {
        var scenario = PlaytestScenarioRegistry.ResolveScenario(
        [
            "--playtest-farm",
            "--playtest-quality",
            "--playtest-door"
        ]);

        Assert.Equal(PlaytestScenarioId.Door, scenario);
    }

    [Fact]
    public void MissingPlaytestFlagKeepsTheNormalStartupFallback()
    {
        var scenario = PlaytestScenarioRegistry.ResolveScenario(
        [
            "--capture-playtest=user://capture.png",
            "--unknown"
        ]);

        Assert.Null(scenario);
    }
}
